defaults:  
  - _self_

#basic setting
inSet: output/IE-output
outSet: output/ET-output 

# OpenAI setting
model: gpt-4.1 #your openAI model
api_key: <sk-xxx> #your openAI API key

# Prompt setting
tag_prompt_folder: tools/ET_prompt
tag_prompt_file: et.jinja

# Prompt store
tag_prompt_store: prompt_store/ET-prompts