defaults:  
  - _self_

# basic setting
inSet: output/EM-output-IOC-protect
outSet: output/LP-output

## oepnai config
model: gpt-4.1 #your openAI model
api_key: <sk-xxx> #your openAI API key


## prompt constructor
link_prompt_folder: tools/LP_prompt
link_prompt_file: link.jinja

## prompt store
link_prompt_set: prompt_store/LP-prompts