defaults:  
  - _self_

# basic setting
inSet: output/ET-output-preprocessed
outSet: output/EM-output

# LLM setting
api_key: <sk-xxx> #your openAI API key
embedding_model: text-embedding-3-large #choose your embedding model

# Merging setting
similarity_threshold: 0.6 #choose your similarity threshold